package game.views;

import javax.swing.JFrame;
import javax.swing.JButton;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.SwingConstants;

public class LevelMenu extends JFrame {
	
	/**
	 * Auto-generated by Eclipse
	 */
	private static final long serialVersionUID = 1L;
	
	public LevelMenu() {
		
		setResizable(false);
		setSize(640, 440);
		setLocationRelativeTo(null);
		
		getContentPane().setLayout(null);
		
		JButton btnNewButton = new JButton("Level 1");
		btnNewButton.setBounds(104, 196, 117, 74);
		getContentPane().add(btnNewButton);
		
		JButton btnNewButton_2 = new JButton("Level 2");
		btnNewButton_2.setBounds(260, 196, 117, 74);
		getContentPane().add(btnNewButton_2);
		
		JButton btnNewButton_1 = new JButton("Level 3");
		btnNewButton_1.setBounds(415, 196, 117, 74);
		getContentPane().add(btnNewButton_1);
		
		
		JLabel lblSelectALevel = new JLabel("Select a Level");
		lblSelectALevel.setHorizontalAlignment(SwingConstants.CENTER);
		lblSelectALevel.setFont(new Font("Tahoma", Font.PLAIN, 16));
		lblSelectALevel.setBounds(260, 55, 117, 33);
		getContentPane().add(lblSelectALevel);
		
	}

	

}
